apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synchronist
spec:
  destination:
    namespace: synchronist
    server: 'https://kubernetes.default.svc'
  source:
    path: synchronist
    repoURL: 'https://github.com/siegy22/argo-test'
    targetRevision: main
    path: synchronist
  project: default
