apiVersion: v1
kind: PersistentVolume
metadata:
  name: synchronist-postgres-data-persisent-volume
spec:
  claimRef:
    name: synchronist-postgres-data-persisent-volume-claim
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pgdata"
